"""Generate the feature documentation and the ``features_v2`` summary from the registry.

``uv run python scripts/write_feature_docs.py`` rewrites ``docs/FEATURES.md``: a short
primer on CAMELS and one table per group with every registered feature's name, formula,
unit, monotone sign, prototype and plain-English explanation. The file is generated, so
it can never drift from the code; ``tests/test_registry_audit.py`` fails when it does.

``uv run python scripts/write_feature_docs.py --summary`` also reads ``features_v2`` and
``labels`` from ``data/parquet/`` and writes ``reports/features_v2_summary.md`` (feature
count, NaN share and p1 / p50 / p99 per feature, and the medians of the P2 features for
banks that failed within four quarters versus those that did not).
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

from bankcanary.features import registry
from bankcanary.features.spec import MONOTONE_TEXT, FeatureSpec
from bankcanary.features.ytd import KEY

ROOT = Path(__file__).resolve().parents[1]
DOCS_PATH = ROOT / "docs" / "FEATURES.md"
SUMMARY_PATH = ROOT / "reports" / "features_v2_summary.md"

#: Registry group -> section heading, in CAMELS order followed by the non-CAMELS groups.
GROUP_TITLES: dict[str, str] = {
    "capital": "Capital adequacy (C)",
    "asset_quality": "Asset quality (A)",
    "management": "Management (M)",
    "earnings": "Earnings (E)",
    "liquidity": "Liquidity (L)",
    "sensitivity": "Sensitivity to market risk (S)",
    "concentration": "Loan concentration",
    "trends": "Trends and persistence",
    "structure": "Structure",
    "macro": "Macro environment",
}

SIGN_TEXT = {1: "+1", -1: "-1", 0: "0"}

INTRO = """# Feature documentation

Generated by `scripts/write_feature_docs.py` from `bankcanary.features.registry`; do not
edit by hand. Every column of `features_v1` (prototype P1) and `features_v2` (P1 + P2) is
listed below in build order within its group.

## What CAMELS is

Bank supervisors in the United States grade every bank on six components, known by the
acronym CAMELS: **C**apital adequacy (the cushion that absorbs losses), **A**sset quality
(how many loans are going bad), **M**anagement (the quality of the decisions being made,
visible in data mostly as growth and expansion choices), **E**arnings (whether the bank
makes money), **L**iquidity (whether it can pay depositors who ask for their money) and
**S**ensitivity to market risk (how much interest-rate moves change the value of what it
holds). The feature groups below follow that structure and add loan concentration, trends
over time, the bank's structure and the macroeconomic backdrop of its home state.

## How to read the tables

- **formula** uses the FDIC field codes of the Call Report (`config/fields.yaml`) and,
  for derived features, the names of other registered features. A `_q` suffix marks an
  income item de-accumulated to one quarter; "annualised" multiplies it by four.
- **unit**: `ratio` is a plain fraction (0.05 = 5 %), `percent` is as published by the
  FDIC, `delta_*` is the change of that unit, `flag` is True / False, `count` is a
  number of quarters.
- **sign** is the monotone direction the constrained gradient-boosting model may enforce:
  `+1` when failure risk rises with the value, `-1` when it falls, `0` when no direction
  is assumed. The same sign is written into every explanation in the registry.
- **proto** is the prototype that introduced the feature (P1 columns form `features_v1`).
"""


def explanation_body(s: FeatureSpec) -> str:
    """The explanation without the trailing monotone sentence (the table has a sign column)."""
    tail = MONOTONE_TEXT[s.monotone]
    text = s.explanation
    if text.endswith(tail):
        text = text[: -len(tail)]
    return text.strip()


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def group_order(specs: list[FeatureSpec]) -> list[str]:
    """Groups in CAMELS order; any group the registry adds later follows in build order."""
    present = []
    for s in specs:
        if s.camels_group not in present:
            present.append(s.camels_group)
    known = [g for g in GROUP_TITLES if g in present]
    return known + [g for g in present if g not in GROUP_TITLES]


def render_group(group: str, specs: list[FeatureSpec]) -> str:
    rows = [s for s in specs if s.camels_group == group]
    title = GROUP_TITLES.get(group, group.replace("_", " ").capitalize())
    lines = [
        f"## {title}",
        "",
        f"{len(rows)} features.",
        "",
        "| name | formula | unit | sign | proto | explanation |",
        "|---|---|---|---|---|---|",
    ]
    for s in rows:
        lines.append(
            f"| `{s.name}` | `{_cell(s.formula)}` | {s.unit} | {SIGN_TEXT[s.monotone]} "
            f"| {s.prototype} | {_cell(explanation_body(s))} |"
        )
    return "\n".join(lines) + "\n"


def render_feature_docs(specs: list[FeatureSpec] | None = None) -> str:
    """The full ``docs/FEATURES.md`` text for ``specs`` (default: the whole registry)."""
    specs = registry.REGISTRY if specs is None else specs
    n_p1 = sum(s.prototype == "P1" for s in specs)
    n_p2 = sum(s.prototype == "P2" for s in specs)
    counts = (
        f"{len(specs)} registered features: {n_p1} P1 (`features_v1`) and {n_p2} P2 "
        f"(`features_v2` = P1 + P2, plus the `ytd_prev_missing` flag in both tables).\n"
    )
    sections = [render_group(g, specs) for g in group_order(specs)]
    return INTRO + "\n" + counts + "\n" + "\n".join(sections)


def summarise_features(features: pd.DataFrame, names: list[str]) -> pd.DataFrame:
    """Per feature: non-null count, NaN share and the 1st / 50th / 99th percentiles.

    Boolean flags are summarised as 0/1 so their percentiles read as the share of True.
    """
    rows = []
    for name in names:
        col = features[name]
        values = col.astype("float64") if col.dtype != "float64" else col
        q = values.quantile([0.01, 0.50, 0.99])
        rows.append(
            {
                "feature": name,
                "n": int(values.notna().sum()),
                "nan_share": float(values.isna().mean()),
                "p1": float(q.iloc[0]),
                "p50": float(q.iloc[1]),
                "p99": float(q.iloc[2]),
            }
        )
    return pd.DataFrame(rows).set_index("feature")


def p2_medians(features: pd.DataFrame, labels: pd.DataFrame, horizon: int = 4) -> pd.DataFrame:
    """Median of every P2 feature for ``y_{H}q`` = 1 versus 0 on label-complete rows.

    Mirrors ``features.build.failure_contrast``: rows that are not label-complete or were
    flagged ``dropped_failed_before_avail`` are excluded, exactly as in training.
    """
    y = f"y_{horizon}q"
    keep = labels[f"label_complete_{horizon}q"].fillna(False).astype(bool) & ~labels[
        "dropped_failed_before_avail"
    ].fillna(True).astype(bool)
    names = registry.feature_names("P2")
    joined = features[KEY + names].merge(labels.loc[keep, KEY + [y]], on=KEY, how="inner")
    frame = joined[names].astype("float64").assign(**{y: joined[y].astype(int)})
    medians = frame.groupby(y)[names].median().T
    medians.columns = [f"median_y{c}" for c in medians.columns]
    counts = frame.groupby(y).size()
    medians.attrs["counts"] = {int(k): int(v) for k, v in counts.items()}
    return medians


def _fmt(x: float) -> str:
    if pd.isna(x):
        return "NaN"
    return f"{x:.4g}" if abs(x) < 1e4 else f"{x:.3e}"


def render_summary(features: pd.DataFrame, labels: pd.DataFrame, horizon: int = 4) -> str:
    """The ``reports/features_v2_summary.md`` text."""
    names = registry.feature_names(version="v2")
    stats = summarise_features(features, names)
    medians = p2_medians(features, labels, horizon)
    counts = medians.attrs.get("counts", {})
    lines = [
        "# features_v2 summary",
        "",
        "Generated by `scripts/write_feature_docs.py --summary` from `data/parquet/features_v2`.",
        "",
        f"- Rows: {len(features):,}; features: {len(names)} "
        f"({len(registry.feature_names('P1'))} P1 + {len(registry.feature_names('P2'))} P2) "
        "plus `ytd_prev_missing`.",
        "- Flags are summarised as 0/1, so their p50 / p99 read as the share of True.",
        "",
        "## NaN share and percentiles per feature",
        "",
        "| feature | n | nan_share | p1 | p50 | p99 |",
        "|---|---|---|---|---|---|",
    ]
    for name, r in stats.iterrows():
        lines.append(
            f"| `{name}` | {int(r['n']):,} | {r['nan_share']:.4f} | {_fmt(r['p1'])} "
            f"| {_fmt(r['p50'])} | {_fmt(r['p99'])} |"
        )
    lines += [
        "",
        f"## P2 medians, failed within {horizon} quarters (y=1) versus not (y=0)",
        "",
        f"Label-complete rows only (`label_complete_{horizon}q`, not "
        f"`dropped_failed_before_avail`): {counts.get(1, 0):,} rows with y=1 and "
        f"{counts.get(0, 0):,} with y=0.",
        "",
        "| feature | median y=1 | median y=0 |",
        "|---|---|---|",
    ]
    for name, r in medians.iterrows():
        lines.append(f"| `{name}` | {_fmt(r['median_y1'])} | {_fmt(r['median_y0'])} |")
    return "\n".join(lines) + "\n"


def write_docs(path: Path = DOCS_PATH) -> Path:
    registry.check_registry()
    path.write_text(render_feature_docs())
    return path


def write_summary(path: Path = SUMMARY_PATH, horizon: int = 4) -> Path:
    from bankcanary.config import load_settings
    from bankcanary.storage.parquet import read_table

    settings = load_settings()
    features = read_table("features_v2", settings=settings)
    labels = read_table("labels", settings=settings)
    path.write_text(render_summary(features, labels, horizon))
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--summary",
        action="store_true",
        help="also write reports/features_v2_summary.md from data/parquet (slow, reads 280 MB)",
    )
    parser.add_argument("--horizon", type=int, default=4)
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    print(f"wrote {write_docs()}")
    if args.summary:
        print(f"wrote {write_summary(horizon=args.horizon)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
